### PR TITLE
update erlang.mk, remove checked in relx

### PR DESCRIPTION
**Pull request by phanimahesh**
Existing version of relx can not build working releases on OTP 21.
Erlang.mk has updated its internal relx since, but we are using a very
very old version of erlang.mk.

This commit updates erlang.mk, and removes the checked in relx.
Erlang.mk will download relx and use it when necessary. It is not
placed in the tree anymore.

### CODE REVIEW

**Comment by Gilbert-Wong** [comment]
Hi, @phanimahesh existing version of relx can build emqx-rel successfully on OTP 21. There is no such problem you stated

**Comment by phanimahesh** [comment]
The releases don't run for me, complaining about missing no dot erlang.boot

**Comment by phanimahesh** [comment]
And even if they do, no harm updating erlang.mk and relx, right?

**Comment by Gilbert-Wong** [comment]
Please fork from emqx/emqx-rel rather than apinf/emq-relx, if you directly clone emqx30 branch of emqx/emqx-rel to your local machine. Still cannot build successfully? Anyway, we would update erlang.mk and relx later.

**Pull request closed without merging**
